- hosts: all
  become: true
  tasks:

    - name: Installing Cinder
      apt: 
        name:
          - cinder-volume
          - python3-mysqldb
        state: latest
        update_cache: yes

    - name: Installing Horizon
      apt:
        name: 
          - openstack-dashboard
        state: latest
        update_cache: yes

    - name: Installing Neutron
      apt:
        name:
          - neutron-server
          - neutron-l3-agent
          - neutron-plugin-ml2
          - neutron-dhcp-agent
          - neutron-linuxbridge-agent
          - python3-neutronclient
        state: latest
        update_cache: yes
